### ISSUE TITLE
How to register valet command in global variable

### ISSUE THREAD

**Issue by Hujjat** [vitr/valet4windows#3]
Hi,
I have installed valet4windows and everything worked fine. I created a laravel project in my desktop, then I run the valet install command. But it's not recognized as bash command. 
How can I register it in global variable, I mean where valet is installed ? 

thank's :)

**Comment by vitr** [comment]
hi @Hujjat ,
do you use git-bash or something similar? regular windows cmd doesn't work here.
in git-bash you can always check the valet path, e.g.
```
$ where valet
C:\Users\Vit\AppData\Roaming\Composer\vendor\bin\valet
C:\Users\Vit\AppData\Roaming\Composer\vendor\bin\valet.bat
```

**Comment by Hujjat** [comment]
Thanks :) 
Using git bash worked perfectly fine. But when I open valet, it deny access.

**Comment by vitr** [comment]
what's the exact error? running git-bash as admin usually helps, btw

**Comment by Hujjat** [comment]
Yeah I ran the git-bash as admin, still not working. Here is the error. I have just created a laravel application named blogger.

![capture](https://cloud.githubusercontent.com/assets/5115878/17687391/04f99ed4-638e-11e6-9543-5650a373a364.PNG)

thanks :)

**Comment by vitr** [comment]
have you got your **C:\Windows\System32\drivers\etc\hosts** file updated?
add this line manually, if it's not there
```
127.0.0.1 blogger.dev
```
because, you're not going to localhost now. I updated the readme:

> Set C:\Windows\System32\drivers\etc\hosts file permissions to allow full control for current user/administrator

if the line doesn't appear there after `valet scan` command, please, let me know, cheers.

**Comment by Hujjat** [comment]
hmm still not working. 
Here is what I have done so far. 
I have changed the hosts file permission to full access, both for administrator and users. than I ran the `valet scan` command in git-bash run as admin. Then I run _`valet open`_ in the laravel project and again same error. :( 

Here is my folder permission picture. 
![capture](https://cloud.githubusercontent.com/assets/5115878/17700229/56021f54-63de-11e6-84d2-2e7dc74c5253.PNG)

**Comment by vitr** [comment]
before `scan` you need `park`(for parent folder) or `link`(for project specific folder).  please, check the contents of the host, is there '127.0.0.1 blogger.dev` entry?

**Comment by Hujjat** [comment]
Nope, those entry doesn't exist. There is only two commented line of code for valet. Here it looks like 
```
# Valet Custom Section
# Valet Custom Section END
```

**Comment by vitr** [comment]
you have to register the parent folder with `park` command, then every subfolder will be accessible on *.dev
add the entry manually as a quick fix, if you want, but you should park anyway.

**Comment by Hujjat** [comment]
I don't know how to park. :( 
please guide me

**Comment by vitr** [comment]
if your folder is blogger, cd out of it ../ and run `valet park`
see the full list of steps (readme)
```
composer global require laravel/installer vitr/valet4windows
mkdir ~/Sites && cd ~/Sites
laravel new blog
valet install
valet park
valet scan 
valet start
cd blog && valet open 
```

**Comment by Hujjat** [comment]
Yeah thank you so much working just fine :)
It was better if you could write those step in lines. I didn't run the park previously. 

thanks for your great help and project :+1:
